version: "3.9"
services:
  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: eav
      POSTGRES_USER: eav
      POSTGRES_PASSWORD: eav
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
