version: "3.9"
services:
  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: jsonb
      POSTGRES_USER: jsonb
      POSTGRES_PASSWORD: jsonb
    ports:
      - "5431:5432"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
